### PR TITLE
chore: fix shellscript comment

### PR DESCRIPTION
**Pull request by KisaragiEffective**

### CODE REVIEW

**Review by fw-immunant — CHANGES_REQUESTED** [review]
Thanks for the fix! You seem to have run afoul of Muphry's Law, though: typo in `$RUST_VER`.

**Comment by KisaragiEffective** [comment]
oof :c

**Comment by fw-immunant** [comment]
Typo fixed.

**Comment by KisaragiEffective** [comment]
thank you :)

**Pull request merged**
