### PR TITLE
Add python `compiledb` example

### LINKED ISSUE #659: Documentation request: Add python `compiledb` as a way to generate `compile-commands.json` from a `Makefile`
I was using c2rust and I was trying to translate this project called [light](https://github.com/haikarainen/light).
~~None of the methods from [the docs](https://c2rust.com/manual/quickstart.html?highlight=intercept#-with--intercept-build) to generate a compile-commands.json worked.~~ 
Turns out the other tools are just a bit more finicky (at least for the project I was working on).

[`compiledb`](https://pypi.org/project/compiledb/) works great.
All I had to do was `compiledb make` (after running `./autogen.sh && ./configure --with-udev` of course).

Could you please add this to the docs?

### PR DESCRIPTION
**Pull request by wildwestrom**
Fixes #659.

### CODE REVIEW

**Review by thedataking — APPROVED** [review]
LGTM, thanks!

**Review by kkysen — CHANGES_REQUESTED** [review]
I think we should clarify that `compiledb` works without having to recompile everything, which `bear` and `intercept-build` require.

**Comment by thedataking** [comment]
> I think we should clarify that `compiledb` works without having to recompile everything, which `bear` and `intercept-build` require.

How the tools work isn't terribly important. `bear` and `intercept-build` do not require recompilation. They require a full (non-incremental) build.

**Comment by kkysen** [comment]
> How the tools work isn't terribly important. `bear` and `intercept-build` do not require recompilation. They require a full (non-incremental) build.

That's what I mean.  I don't think `compiledb` requires a full build.

That's where this issue came from.  `bear` was being used in an incremental build so it wasn't working, but `compiledb` did.

**Comment by thedataking** [comment]
> That's what I mean. I don't think compiledb requires a full build.

Correct. However, it is incumbent on the user to learn how to use each tool using the relevant documentation. Our README simply provides pointers to each tool that may or may not be useful.

**Comment by kkysen** [comment]
> Correct. However, it is incumbent on the user to learn how to use each tool using the relevant documentation. Our README simply provides pointers to each tool that may or may not be useful.

That's true, but they often don't, and a lot of the opened issues end up being about not able to create the compilation database correctly.  An extra sentence of clarification won't hurt.

**Pull request merged**
