### PR TITLE
Enabled `long double` test by default

### PR DESCRIPTION
**Pull request by kkysen**
`./scripts/test_translator.py tests/` previously skipped the `tests/longdouble` test unless `--test-longdoubles` was passed, because the `long double` test didn't always work.  It should be fixed now, so we can get rid of the `--test-longdoubles` option and have it be tested by default now.  The tests all work locally (Ubuntu/Linux), but I'm waiting to check if it works in CI on Darwin/macOS, too.

### CODE REVIEW

**Comment by kkysen** [comment]
It works on everything except for Darwin and Fedora, where the [`f128`](https://github.com/jkarns275/f128) crate doesn't compile because `<quadmath.h>` isn't available.  On Darwin, it appears `libgfortran` and `libquadmath` might also be missing, because they are reported as unused linker arguments.  This is probably the same error, needing GCC headers, that was the reason why `tests/longdouble` was disabled by default in the first place.  We should see if we can fix these issues or disable `tests/longdouble` only on Darwin and Fedora.

[Darwin CI](https://dev.azure.com/immunant/c2rust/_build/results?buildId=1741&view=logs&j=02bad918-85c8-5a4b-30eb-93cb7f58f78e&t=92312585-ff34-5e62-11b6-5ebd1acc3131&l=348):

Shortened Output:

```shell
> cc -O0 -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64 -Wall -Wextra -Bstatic -lgfortran -lquadmath -o /Users/runner/work/1/s/tests/longdouble/target/release/build/f128_internal-2a483563073f0a34/out/src/f128.o -c src/f128.c
clang: warning: -lgfortran: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -lquadmath: 'linker' input unused [-Wunused-command-line-argument]
src/f128.c:2:10: fatal error: 'quadmath.h' file not found
#include <quadmath.h>
         ^~~~~~~~~~~~
1 error generated.
```

<details>
<summary>Full Output:</summary>

```shell
warning: clang: warning: -lgfortran: 'linker' input unused [-Wunused-command-line-argument]
warning: clang: warning: -lquadmath: 'linker' input unused [-Wunused-command-line-argument]
warning: src/f128.c:2:10: fatal error: 'quadmath.h' file not found
warning: #include <quadmath.h>
warning:          ^~~~~~~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `f128_internal v0.2.2`

Caused by:
  process didn't exit successfully: `/Users/runner/work/1/s/tests/longdouble/target/release/build/f128_internal-f661bd455c715f27/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-apple-darwin")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-Wall" "-Wextra" "-Bstatic" "-lgfortran" "-lquadmath" "-o" "/Users/runner/work/1/s/tests/longdouble/target/release/build/f128_internal-2a483563073f0a34/out/src/f128.o" "-c" "src/f128.c"
  cargo:warning=clang: warning: -lgfortran: 'linker' input unused [-Wunused-command-line-argument]
  cargo:warning=clang: warning: -lquadmath: 'linker' input unused [-Wunused-command-line-argument]
  cargo:warning=src/f128.c:2:10: fatal error: 'quadmath.h' file not found
  cargo:warning=#include <quadmath.h>
  cargo:warning=         ^~~~~~~~~~~~
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr


  error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-Wall" "-Wextra" "-Bstatic" "-lgfortran" "-lquadmath" "-o" "/Users/runner/work/1/s/tests/longdouble/target/release/build/f128_internal-2a483563073f0a34/out/src/f128.o" "-c" "src/f128.c" with args "cc" did not execute successfully (status code exit status: 1).
```

</details>

[Fedora CI](https://dev.azure.com/immunant/c2rust/_build/results?buildId=1741&view=logs&j=1bc19d9b-b6c8-52d0-07d6-07754b7d13fb&t=0ea4c305-8a5c-5f7f-3862-8dc92e4cf4f2&l=241):

Shortened Output:

```shell
> cc -O0 -ffunction-sections -fdata-sections -fPIC -m64 -Wall -Wextra -Bstatic -lgfortran -lquadmath -o /__w/1/s/tests/longdouble/target/release/build/f128_internal-996f96ded83be736/out/src/f128.o -c src/f128.c
src/f128.c:2:10: fatal error: quadmath.h: No such file or directory
    2 | #include <quadmath.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```

<details>
<summary>Full Output:</summary>

```shell
warning: src/f128.c:2:10: fatal error: quadmath.h: No such file or directory
warning:     2 | #include <quadmath.h>
warning:       |          ^~~~~~~~~~~~
warning: compilation terminated.

error: failed to run custom build command for `f128_internal v0.2.2`

Caused by:
  process didn't exit successfully: `/__w/1/s/tests/longdouble/target/release/build/f128_internal-dda1d88daf824757/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-Bstatic" "-lgfortran" "-lquadmath" "-o" "/__w/1/s/tests/longdouble/target/release/build/f128_internal-996f96ded83be736/out/src/f128.o" "-c" "src/f128.c"
  cargo:warning=src/f128.c:2:10: fatal error: quadmath.h: No such file or directory
  cargo:warning=    2 | #include <quadmath.h>
  cargo:warning=      |          ^~~~~~~~~~~~
  cargo:warning=compilation terminated.
  exit status: 1

  --- stderr


  error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-Bstatic" "-lgfortran" "-lquadmath" "-o" "/__w/1/s/tests/longdouble/target/release/build/f128_internal-996f96ded83be736/out/src/f128.o" "-c" "src/f128.c" with args "cc" did not execute successfully (status code exit status: 1).
```

</details>

[`src/f128.c`](https://github.com/jkarns275/f128/blob/master/f128_internal/src/f128.c)

Relevant Lines (top of file):
```c
#include <stdio.h>
#include <quadmath.h>
#include <stdlib.h>
#include <stdint.h>
#include <math.h>
typedef __float128 f128;
extern int quadmath_snprintf (char *s, size_t size, const char *format, ...);
```

<details>
<summary>Full File:</summary>

```c
#include <stdio.h>
#include <quadmath.h>
#include <stdlib.h>
#include <stdint.h>
#include <math.h>
typedef __float128 f128;
extern int quadmath_snprintf (char *s, size_t size, const char *format, ...);

typedef union _Wrapper {
  f128 value;
  unsigned __int128 dat;
  char dat_alt[16];
} __attribute__ ((aligned (16))) Wrapper;

Wrapper strtoflt128_f(const char *s) {
  return (Wrapper) { strtoflt128(s, NULL) };
}

#define x_to_f128(x, n) Wrapper n##_to_f128(x a) {    \
    Wrapper d;                                        \
    d.value = (f128) a;                               \
    return d;                                         \
}

#define f128_to_x(x, n) x f128_to_##n(Wrapper a) {   \
  return (x) a.value;\
}

int qtostr(char* s, size_t size, const char *format, Wrapper r) {
  return quadmath_snprintf(s, size, format, r.value);
}

f128_to_x(int8_t, i8)
f128_to_x(int16_t, i16)
f128_to_x(int32_t, i32)
f128_to_x(int64_t, i64)
f128_to_x(uint8_t, u8)
f128_to_x(uint16_t, u16)
f128_to_x(uint32_t, u32)
f128_to_x(uint64_t, u64)
f128_to_x(float, f32)
f128_to_x(double, f64)
f128_to_x(unsigned __int128, u128)
f128_to_x(__int128, i128)
f128_to_x(size_t, usize)
f128_to_x(ssize_t, isize)

Wrapper u128_to_f128(unsigned __int128 a) {
    Wrapper d;
    d.value = (f128) a;
    return d;
}

Wrapper i128_to_f128(__int128 a) {
    Wrapper d;
    d.value = (f128) a;
    return d;
}


x_to_f128(int8_t, i8);
x_to_f128(int16_t, i16);
x_to_f128(int32_t, i32);
x_to_f128(int64_t, i64);
x_to_f128(uint8_t, u8);
x_to_f128(uint16_t, u16);
x_to_f128(uint32_t, u32);
x_to_f128(uint64_t, u64);
x_to_f128(float, f32);
x_to_f128(double, f64);
//x_to_f128(__int128, i128)
//x_to_f128(unsigned __int128, u128)
x_to_f128(size_t, usize);
x_to_f128(ssize_t, isize);

 Wrapper f128_add(Wrapper a, Wrapper b){
  Wrapper x;
  x.value = a.value + b.value;
  return x;
}

 Wrapper f128_sub(Wrapper a, Wrapper b){
  Wrapper x;
  x.value = a.value - b.value;
  return x;
}

 Wrapper f128_mul(Wrapper a, Wrapper b){
  Wrapper x;
  x.value = a.value * b.value;
  return x;
}

 Wrapper f128_div(Wrapper a, Wrapper b){
  Wrapper x;
  x.value = a.value / b.value;
  return x;
}

 Wrapper f128_modulo(Wrapper a, Wrapper b){
  Wrapper x;
  x.value = fmodq(a.value, b.value);
  return x;
}

void f128_to_str(Wrapper a, size_t n, char* buf, const char* format) {
  quadmath_snprintf(buf, n, format, a);
}
/* Prototypes for real functions */

 Wrapper acosq_f(Wrapper a) {
  return (Wrapper) { acosq(a.value) };
}
 Wrapper acoshq_f(Wrapper a) {
  return (Wrapper) { acoshq(a.value) };
}
 Wrapper asinq_f (Wrapper a) {
  return (Wrapper) { asinq(a.value) };
}
 Wrapper asinhq_f (Wrapper a) {
   return (Wrapper) { asinhq(a.value) };
}
 Wrapper atanq_f (Wrapper a) {
  return (Wrapper) { atanq(a.value) };
}
 Wrapper atanhq_f (Wrapper a) {
  return (Wrapper) { atanhq(a.value) };
}
 Wrapper atan2q_f (Wrapper a, Wrapper b) {
  return (Wrapper) { atan2q(a.value, b.value) };
}
 Wrapper cbrtq_f (Wrapper a) {
  return (Wrapper) { cbrtq(a.value) };
}
 Wrapper ceilq_f (Wrapper a) {
  return (Wrapper) { ceilq(a.value) };
}
 Wrapper copysignq_f (Wrapper a, Wrapper b) {
  return (Wrapper) { copysignq(a.value, b.value) };
}
 Wrapper coshq_f (Wrapper a) {
  return (Wrapper) { coshq(a.value) };
}
 Wrapper cosq_f (Wrapper a) {
  return (Wrapper) { cosq(a.value) };
}
 Wrapper erfq_f (Wrapper a) {
  return (Wrapper) { erfq(a.value) };
}
 Wrapper erfcq_f (Wrapper a) {
  return (Wrapper) { erfcq(a.value) };
}
 Wrapper expq_f (Wrapper a) {
  return (Wrapper) { expq(a.value) };
}
 Wrapper expm1q_f (Wrapper a) {
  return (Wrapper) { expm1q(a.value) };
}
 Wrapper fabsq_f (Wrapper a) {
  return (Wrapper) { fabsq(a.value) };
}
 Wrapper fdimq_f (Wrapper a, Wrapper b) {
  return (Wrapper) { fdimq(a.value, b.value) };
}
 int finiteq_f (Wrapper a) {
  return finiteq(a.value);
}
 Wrapper floorq_f (Wrapper a) {
  return (Wrapper) { floorq(a.value) };
}
 Wrapper fmaq_f (Wrapper a, Wrapper b, Wrapper c) {
  return (Wrapper) { fmaq(a.value, b.value, c.value) };
}
 Wrapper fmaxq_f (Wrapper a, Wrapper b) {
  return (Wrapper) { fmaxq(a.value, b.value) };
}
 Wrapper fminq_f (Wrapper a, Wrapper b) {
  return (Wrapper) { fminq(a.value, b.value) };
}
 Wrapper fmodq_f (Wrapper a, Wrapper b) {
  return (Wrapper) { fmodq(a.value, b.value) };
}
 Wrapper frexpq_f (Wrapper a, int * b) {
  return (Wrapper) { frexpq(a.value, b) };
}
 Wrapper hypotq_f (Wrapper a, Wrapper b) {
  return (Wrapper) { hypotq(a.value, b.value) };
}
 int isinfq_f (Wrapper a) {
  return isinfq(a.value);
}
 int ilogbq_f (Wrapper a) {
  return ilogbq(a.value);
}
 int isnanq_f (Wrapper a) {
  return isnanq(a.value);
}
 Wrapper j0q_f (Wrapper a) {
  return (Wrapper) { j0q(a.value) };
}
 Wrapper j1q_f (Wrapper a) {
  return (Wrapper) { j1q(a.value) };
}
 Wrapper jnq_f (int a, Wrapper b) {
  return (Wrapper) { jnq(a, b.value) };
}
 Wrapper ldexpq_f (Wrapper a, int b) {
  return (Wrapper) { ldexpq(a.value, b) };
}
 Wrapper lgammaq_f (Wrapper a) {
  return (Wrapper) { lgammaq(a.value) };
}
 long long int llrintq_f (Wrapper a) {
  return llrintq(a.value);
}
 long long int llroundq_f (Wrapper a) {
  return llroundq(a.value);
}

/*
 Wrapper logbq_f (Wrapper a) {
  return (Wrapper) { logbq(a.value) };
}
*/
 Wrapper logq_f (Wrapper a) {
   return (Wrapper) { logq(a.value) };
}
 Wrapper log10q_f (Wrapper a) {
  return (Wrapper) { log10q(a.value) };
}
 Wrapper log2q_f (Wrapper a) {
  return (Wrapper) { log2q(a.value) };
}
 Wrapper log1pq_f (Wrapper a) {
  return (Wrapper) { log1pq(a.value) };
}
 long int lrintq_f (Wrapper a) {
  return lrintq(a.value);
}
 long int lroundq_f (Wrapper a) {
  return lroundq(a.value);
}
 Wrapper modfq_f (Wrapper a, Wrapper * b) {
  return (Wrapper) { modfq(a.value, (f128*) b) };
}
 Wrapper nanq_f (const char * c) {
  return (Wrapper) { nanq(c) };
}
 Wrapper nearbyintq_f (Wrapper a) {
  return (Wrapper) { nearbyintq(a.value) };
}
 Wrapper nextafterq_f (Wrapper a, Wrapper b) {
  return (Wrapper) { nextafterq(a.value, b.value) };
}
 Wrapper powq_f (Wrapper a, Wrapper b) {
  return (Wrapper) { powq(a.value, b.value) };
}
 Wrapper remainderq_f (Wrapper a, Wrapper b) {
  return (Wrapper) { remainderq(a.value, b.value) };
}
 Wrapper remquoq_f (Wrapper a, Wrapper b, int * c) {
  return (Wrapper) { remquoq(a.value, b.value, c) };
}
 Wrapper rintq_f (Wrapper a) {
  return (Wrapper) { rintq(a.value) };
}
 Wrapper roundq_f (Wrapper a) {
  return (Wrapper) { roundq(a.value) };
}
 Wrapper scalblnq_f (Wrapper a, long int b) {
  return (Wrapper) { scalblnq(a.value, b) };
}
 Wrapper scalbnq_f (Wrapper a, int b) {
  return (Wrapper) { scalbnq(a.value, b) };
}
 int signbitq_f (Wrapper a) {
  return signbitq(a.value);
}
 void sincosq_f (Wrapper a, Wrapper * b, Wrapper * c) {
  sincosq(a.value, (f128*) b, (f128*) c);
}
 Wrapper sinhq_f (Wrapper a) {
  return (Wrapper) { sinhq(a.value) };
}
 Wrapper sinq_f (Wrapper a) {
  return (Wrapper) { sinq(a.value) };
}
 Wrapper sqrtq_f (Wrapper a) {
  return (Wrapper) { sqrtq(a.value) };
}
 Wrapper tanq_f (Wrapper a) {
  return (Wrapper) { tanq(a.value) };
}
 Wrapper tanhq_f (Wrapper a) {
  return (Wrapper) { tanhq(a.value) };
}
 Wrapper tgammaq_f (Wrapper a) {
  return (Wrapper) { tgammaq(a.value) };
}
 Wrapper truncq_f (Wrapper a) {
  return (Wrapper) { truncq(a.value) };
}
 Wrapper y0q_f (Wrapper a) {
  return (Wrapper) { y0q(a.value) };
}
 Wrapper y1q_f (Wrapper a) {
  return (Wrapper) { y1q(a.value) };
}
 Wrapper ynq_f(int a, Wrapper b) {
  return (Wrapper) { ynq(a, b.value) };
}

unsigned char gtq(Wrapper a, Wrapper b) {
    return (unsigned char) (a.value > b.value);
}

unsigned char gteq(Wrapper a, Wrapper b) {
    return (unsigned char) (a.value >= b.value);
}
unsigned char ltq(Wrapper a, Wrapper b) {
    return (unsigned char) (a.value < b.value);
}
unsigned char lteq(Wrapper a, Wrapper b) {
    return (unsigned char) (a.value <= b.value);
}
unsigned char eqq(Wrapper a, Wrapper b) {
    return (unsigned char) (a.value == b.value);
}
unsigned char neqq(Wrapper a, Wrapper b) {
    return (unsigned char) (a.value != b.value);
}
```

</details>

**Comment by fw-immunant** [comment]
The darwin issue looks like https://github.com/jkarns275/f128/issues/4#issuecomment-707273263.

**Comment by kkysen** [comment]
Yeah, we may want to just skip macOS.  I'll see if I can get Fedora to work if it's not too hard.

**Comment by fw-immunant** [comment]
On Fedora, it seems like `quadmath.h` isn't in the default include search path. It's usually somewhere along the lines of `/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.0/include/quadmath.h`.

What does running `echo | gcc -E -Wp,-v -` (to see the gcc include search paths) give in our Fedora docker container?

**Comment by kkysen** [comment]
`yum install libquadmath-devel` seems to fix it (building the `f128` crate now works, which should be the only issue).

**Comment by kkysen** [comment]
It's still failing CI, but that's because the docker images need to be updated with the changes to the provisioning scripts here. @thedataking

**Review by thedataking — APPROVED** [review]

**Comment by kkysen** [comment]
Passed CI with updated docker images, so merging now.

**Pull request merged**
