### PR TITLE
Set rpath to find rustc private crates at runtime

### PR DESCRIPTION
**Pull request by kkysen**
Fixes https://github.com/immunant/c2rust/issues/514.

Now `c2rust-pdg` and `c2rust-instrument` work without needing to set `LD_LIBRARY_PATH`.

### CODE REVIEW

**Comment by kkysen** [comment]
The `RUSTLIB` export and `c2rust/build.rs` were already handled in https://github.com/immunant/c2rust/pull/517, which this PR is merging on top of.

For the `LD_LIBRARY_PATH` handling in `invoke_subcommand` from `c2rust/src/main.rs`, I didn't catch that.  Thanks!  I'll remove that, too, now.

**Comment by fw-immunant** [comment]
`RUSTLIB` should no longer be necessary if we use rpath instead of `LD_LIBRARY_PATH`, because the code setting the latter in `invoke_subcommand` was the only place the `RUSTLIB` env var was ever read.

**Comment by kkysen** [comment]
`invoke_subcommand` in `c2rust/src/main.rs` uses `RUSTLIB` for `LD_LIBRARY_PATH`, where `RUSTLIB` is `$(rustc --print sysroot)/lib/rustlib/$TARGET/lib/`.  The others use `$(rustc --print sysroot)/lib/`.  Is there a reason why the rustlib one is used?

The difference (below) appears to be that `lib` contains `libLLVM*.so`, as well as the other `*.so`s needed, while `rustlib` does not contain `libLLVM*.so`, the other same `*.so`s, but also a ton of `*.rlib`s.

```shell
kkysen in 🌐 donna in c2rust on  kkysen/rustc-private-link-rpath via 🐍 v3.10.4 via 🦀 v1.60.0-nightly via 🐏 5GiB/39GiB | 472MiB/2GiB took 18ms
at 12:17:32 PM ❯ ll $(rustc --print sysroot)/lib
.rw-r--r-- 101M kkysen  7 Jun 12:56 libLLVM-13-rust-1.60.0-nightly.so
.rw-r--r-- 119M kkysen  7 Jun 12:56 librustc_driver-f43b82d7671d3119.so
.rw-r--r-- 9.2M kkysen  7 Jun 12:56 libstd-fad6565a4a24ca7c.so
.rw-r--r-- 2.9M kkysen  7 Jun 12:56 libtest-b81f71b2dfdd83d8.so
drwxrwxr-x    - kkysen 28 Jun 18:02 rustlib/
```

```shell
kkysen in 🌐 donna in c2rust on  kkysen/rustc-private-link-rpath via 🐍 v3.10.4 via 🦀 v1.60.0-nightly via 🐏 5GiB/39GiB | 461MiB/2GiB took 52ms
at 12:23:06 PM ❯ ll $(rustc --print sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/lib
.rw-r--r-- 345k kkysen  7 Jun 12:56 libaddr2line-a53256cbf12c5e40.rlib
.rw-r--r--  47k kkysen  7 Jun 12:56 libadler-63c9c6ed2f71b398.rlib
.rw-r--r--  47k kkysen  8 Jun 10:20 libadler-ddb9690513272852.rlib
.rw-r--r-- 494k kkysen  8 Jun 10:20 libahash-2b45151b08eb25da.rlib
.rw-r--r-- 2.5M kkysen  8 Jun 10:20 libaho_corasick-2c981739337429f3.rlib
.rw-r--r-- 5.0M kkysen  7 Jun 12:56 liballoc-cd90985afc868a6d.rlib
.rw-r--r-- 525k kkysen  8 Jun 10:20 libannotate_snippets-2160b0f3d88b862a.rlib
.rw-r--r-- 368k kkysen  8 Jun 10:20 libansi_term-af9b22a169fb6d2a.rlib
.rw-r--r-- 369k kkysen  8 Jun 10:20 libarrayvec-af9dd8b3a608bac7.rlib
.rw-r--r--  13k kkysen  8 Jun 10:20 libatty-15665a011ba3b101.rlib
.rw-r--r--  52k kkysen  8 Jun 10:20 libbitflags-5a67895375a88130.rlib
.rw-r--r--  45k kkysen  8 Jun 10:20 libblock_buffer-2945cde848e99d80.rlib
.rw-r--r-- 1.0M kkysen  8 Jun 10:20 libcc-ba0779010b225ae2.rlib
.rw-r--r--  10k kkysen  7 Jun 12:56 libcfg_if-9166aee941371fa5.rlib
.rw-r--r-- 8.1k kkysen  8 Jun 10:20 libcfg_if-914531ba6af3c18f.rlib
.rw-r--r-- 7.9k kkysen  8 Jun 10:20 libcfg_if-cb5566fad244195f.rlib
.rwxr-xr-x  14M kkysen  8 Jun 10:20 libchalk_derive-b1ba70b71b38b458.so*
.rw-r--r-- 1.9M kkysen  8 Jun 10:20 libchalk_engine-b6c24b4a37949a55.rlib
.rw-r--r-- 4.1M kkysen  8 Jun 10:20 libchalk_ir-ac1bd8a892812890.rlib
.rw-r--r-- 5.2M kkysen  8 Jun 10:20 libchalk_solve-a77c8a5274fec2a8.rlib
.rw-r--r-- 3.3M kkysen  7 Jun 12:56 libcompiler_builtins-2e57f9284f7a2443.rlib
.rw-r--r--  56M kkysen  7 Jun 12:56 libcore-0e3656b1fda5fd7b.rlib
.rw-r--r--  21k kkysen  8 Jun 10:20 libcpuid_bool-f51b5b2ef5b54da3.rlib
.rw-r--r-- 233k kkysen  8 Jun 10:20 libcrc32fast-ecdb7e3b06e86025.rlib
.rw-r--r-- 289k kkysen  8 Jun 10:20 libcrossbeam_deque-92fb24c850c14659.rlib
.rw-r--r-- 646k kkysen  8 Jun 10:20 libcrossbeam_epoch-c1be4659f39485f8.rlib
.rw-r--r-- 695k kkysen  8 Jun 10:20 libcrossbeam_utils-29986c396b36ef44.rlib
.rwxr-xr-x 8.3M kkysen  8 Jun 10:20 libcstr-547a61b22dae33cd.so*
.rw-r--r-- 411k kkysen  8 Jun 10:20 libdatafrog-b48d6bde7e7f113d.rlib
.rw-r--r-- 105k kkysen  8 Jun 10:20 libdigest-d06e63f10c6186ae.rlib
.rw-r--r-- 182k kkysen  8 Jun 10:20 libeither-6ae66b7e3957ba83.rlib
.rw-r--r-- 332k kkysen  8 Jun 10:20 libena-038579a3df985bd9.rlib
.rw-r--r-- 649k kkysen  8 Jun 10:20 libfallible_iterator-eb34647a8f1b358d.rlib
.rw-r--r-- 173k kkysen  8 Jun 10:20 libfixedbitset-4f6da4c7cdb27806.rlib
.rw-r--r-- 965k kkysen  8 Jun 10:20 libflate2-dd9fcce81590fc75.rlib
.rw-r--r-- 790k kkysen  8 Jun 10:20 libgeneric_array-af3d1d8febe6a96b.rlib
.rw-r--r-- 1.2M kkysen  7 Jun 12:56 libgetopts-69c91652c37d6e21.rlib
.rw-r--r-- 449k kkysen  8 Jun 10:20 libgetopts-23592201b2e2656d.rlib
.rw-r--r-- 135k kkysen  8 Jun 10:20 libgetrandom-41db5307dd3975e5.rlib
.rw-r--r--  10M kkysen  8 Jun 10:20 libgimli-9223d200a0831f63.rlib
.rw-r--r-- 7.1M kkysen  7 Jun 12:56 libgimli-d076501d614ddd5d.rlib
.rw-r--r-- 909k kkysen  8 Jun 10:20 libgsgdt-277edfdd58af29a8.rlib
.rw-r--r-- 1.1M kkysen  8 Jun 10:20 libhashbrown-833fb51ec54757f2.rlib
.rw-r--r-- 1.4M kkysen  7 Jun 12:56 libhashbrown-c52b4818022f32c3.rlib
.rw-r--r--  16k kkysen  8 Jun 10:20 libif_chain-9626a9ae63e22616.rlib
.rw-r--r-- 877k kkysen  8 Jun 10:20 libindexmap-e023808e57cabbd5.rlib
.rw-r--r-- 9.8k kkysen  8 Jun 10:20 libinstant-c942a5918956a983.rlib
.rw-r--r-- 3.3M kkysen  8 Jun 10:20 libitertools-c612651cbfce3ff5.rlib
.rw-r--r-- 142k kkysen  8 Jun 10:20 libitoa-d47967e7d214e806.rlib
.rw-r--r-- 284k kkysen  8 Jun 10:20 libjobserver-bdf04429f9edfbd6.rlib
.rw-r--r--  29k kkysen  8 Jun 10:20 liblazy_static-dc894e58f51a1037.rlib
.rw-r--r-- 3.9M kkysen  8 Jun 10:20 liblibc-504493b56c0854a6.rlib
.rw-r--r-- 4.0M kkysen  7 Jun 12:56 liblibc-e869a247063ed69a.rlib
.rw-r--r-- 236k kkysen  8 Jun 10:20 liblibloading-d950800ed6890ecb.rlib
.rw-r--r-- 507k kkysen  8 Jun 10:20 liblock_api-1ac4b468ebe98bf4.rlib
.rw-r--r-- 313k kkysen  8 Jun 10:20 liblog-4b21e45b9788cc94.rlib
.rw-r--r--  77k kkysen  8 Jun 10:20 libmatchers-d9cb0b5ac06214ae.rlib
.rw-r--r-- 112k kkysen  8 Jun 10:20 libmd5-17cfec90647735bb.rlib
.rw-r--r-- 606k kkysen  8 Jun 10:20 libmeasureme-55b9bac783642d28.rlib
.rw-r--r-- 1.8M kkysen  8 Jun 10:20 libmemchr-032b1dedf8f19b44.rlib
.rw-r--r-- 1.6M kkysen  7 Jun 12:56 libmemchr-a92344eafcadd40d.rlib
.rw-r--r-- 158k kkysen  8 Jun 10:20 libmemmap2-ba1196d9b491778b.rlib
.rw-r--r--  30k kkysen  8 Jun 10:20 libmemoffset-2ab880f92857c8e9.rlib
.rw-r--r-- 941k kkysen  7 Jun 12:56 libminiz_oxide-8fd2f24f083ee871.rlib
.rw-r--r-- 799k kkysen  8 Jun 10:20 libminiz_oxide-5747c0682c7ebd16.rlib
.rw-r--r-- 150k kkysen  8 Jun 10:20 libnum_cpus-f9351f4c0cb2b7d4.rlib
.rw-r--r--  11M kkysen  8 Jun 10:20 libobject-25a121a8b141082d.rlib
.rw-r--r-- 8.5M kkysen  7 Jun 12:56 libobject-ac6764d7272415e2.rlib
.rw-r--r-- 405k kkysen  8 Jun 10:20 libodht-d246212fd0380093.rlib
.rw-r--r-- 232k kkysen  8 Jun 10:20 libonce_cell-182cfaa605d627b2.rlib
.rw-r--r-- 4.7k kkysen  8 Jun 10:20 libopaque_debug-39d90e9d57b69243.rlib
.rw-r--r--  17k kkysen  7 Jun 12:56 libpanic_abort-6cc689e90dd0a894.rlib
.rw-r--r-- 100k kkysen  7 Jun 12:56 libpanic_unwind-7333b08131ad69c0.rlib
.rw-r--r-- 481k kkysen  8 Jun 10:20 libparking_lot-172ce61375fb4c47.rlib
.rw-r--r-- 328k kkysen  8 Jun 10:20 libparking_lot_core-58c2a43d15a01e39.rlib
.rw-r--r--  14k kkysen  8 Jun 10:20 libpathdiff-5067d15b9c773a3c.rlib
.rw-r--r-- 693k kkysen  8 Jun 10:20 libperf_event_open_sys-d7b1112b449af63c.rlib
.rw-r--r-- 3.1M kkysen  8 Jun 10:20 libpetgraph-a3376ba728eae166.rlib
.rw-r--r-- 105k kkysen  8 Jun 10:20 libpin_project_lite-3b0fb95afe1403cd.rlib
.rw-r--r-- 465k kkysen  8 Jun 10:20 libpolonius_engine-9fe37c33cce45fbf.rlib
.rw-r--r-- 1.4M kkysen  8 Jun 10:20 libppv_lite86-b01d953d8879b478.rlib
.rw-r--r-- 7.9M kkysen  7 Jun 12:56 libproc_macro-af6ab5476d57a294.rlib
.rw-r--r-- 393k kkysen  7 Jun 12:56 libprofiler_builtins-2891588bde8560d8.rlib
.rw-r--r--  43k kkysen  8 Jun 10:20 libpsm-492d70aa7196ead9.rlib
.rw-r--r--  78k kkysen  8 Jun 10:20 libpunycode-56ec4aa4b5b83371.rlib
.rw-r--r-- 2.0M kkysen  8 Jun 10:20 librand-5ac6db8057755291.rlib
.rw-r--r-- 311k kkysen  8 Jun 10:20 librand_chacha-74cad477e3979675.rlib
.rw-r--r-- 231k kkysen  8 Jun 10:20 librand_core-9e45ec4c929f43bc.rlib
.rw-r--r-- 559k kkysen  8 Jun 10:20 librand_xoshiro-176fe8e30202d6d0.rlib
.rw-r--r-- 3.6M kkysen  8 Jun 10:20 libregex-b0a14b03670ffe5f.rlib
.rw-r--r-- 2.3M kkysen  8 Jun 10:20 libregex_automata-34e1a599e67a60ef.rlib
.rw-r--r-- 9.4M kkysen  8 Jun 10:20 libregex_syntax-e9125de09688c13c.rlib
.rw-r--r-- 4.1k kkysen  8 Jun 10:20 libremove_dir_all-d03d456cb5964d1a.rlib
.rw-r--r-- 2.3M kkysen  8 Jun 10:20 librls_data-d47903b503a17453.rlib
.rw-r--r-- 820k kkysen  8 Jun 10:20 librls_span-cde7d1bd6cfbb435.rlib
.rw-r--r-- 5.2M kkysen  7 Jun 12:56 librustc-nightly_rt.asan.a
.rw-r--r-- 1.8M kkysen  7 Jun 12:56 librustc-nightly_rt.lsan.a
.rw-r--r-- 4.1M kkysen  7 Jun 12:56 librustc-nightly_rt.msan.a
.rw-r--r-- 5.3M kkysen  7 Jun 12:56 librustc-nightly_rt.tsan.a
.rw-r--r-- 854k kkysen  8 Jun 10:20 librustc_apfloat-f239f1f2e7fda261.rlib
.rw-r--r-- 112k kkysen  8 Jun 10:20 librustc_arena-b376098859728f82.rlib
.rw-r--r-- 8.4M kkysen  8 Jun 10:20 librustc_ast-75a7ccbbfe13e38c.rlib
.rw-r--r-- 4.8M kkysen  8 Jun 10:20 librustc_ast_lowering-87c9a28cf7b65b05.rlib
.rw-r--r-- 2.5M kkysen  8 Jun 10:20 librustc_ast_passes-9199b3e7ca147c7b.rlib
.rw-r--r-- 1.5M kkysen  8 Jun 10:20 librustc_ast_pretty-e317d9ae15530272.rlib
.rw-r--r-- 975k kkysen  8 Jun 10:20 librustc_attr-1f8e883050b98178.rlib
.rw-r--r--  23M kkysen  8 Jun 10:20 librustc_borrowck-fb4d06cc84884197.rlib
.rw-r--r-- 6.2M kkysen  8 Jun 10:20 librustc_builtin_macros-9ca39e67e6719910.rlib
.rw-r--r--  12M kkysen  8 Jun 10:20 librustc_codegen_llvm-158383575cfdec7c.rlib
.rw-r--r-- 8.7M kkysen  8 Jun 10:20 librustc_codegen_ssa-eb51af6e707f0afb.rlib
.rw-r--r--  13M kkysen  8 Jun 10:20 librustc_const_eval-ae43cbe448657510.rlib
.rw-r--r-- 3.1M kkysen  8 Jun 10:20 librustc_data_structures-0eca6d9041c2706f.rlib
.rw-r--r-- 356k kkysen  8 Jun 10:20 librustc_demangle-d369a30165b591fd.rlib
.rw-r--r-- 855k kkysen  7 Jun 12:56 librustc_demangle-dc343399b5db12bf.rlib
.rwxr-xr-x 119M kkysen  8 Jun 10:20 librustc_driver-f43b82d7671d3119.so*
.rw-r--r-- 1.2M kkysen  8 Jun 10:20 librustc_error_codes-702247fce1933fd7.rlib
.rw-r--r-- 3.5M kkysen  8 Jun 10:20 librustc_errors-f9752317208b0f94.rlib
.rw-r--r-- 9.7M kkysen  8 Jun 10:20 librustc_expand-3628a7c9d2eb3f7e.rlib
.rw-r--r-- 1.5M kkysen  8 Jun 10:20 librustc_feature-85170dfd879d07ef.rlib
.rw-r--r--  24k kkysen  8 Jun 10:20 librustc_fs_util-3c3c845973339629.rlib
.rw-r--r-- 192k kkysen  8 Jun 10:20 librustc_graphviz-aa0e990dee9b7b2e.rlib
.rw-r--r--  27k kkysen  8 Jun 10:20 librustc_hash-8ff78166d21da7a2.rlib
.rw-r--r-- 5.1M kkysen  8 Jun 10:20 librustc_hir-a31cab612d8c1e00.rlib
.rw-r--r-- 837k kkysen  8 Jun 10:20 librustc_hir_pretty-63c6e992b3febf1b.rlib
.rw-r--r-- 3.0M kkysen  8 Jun 10:20 librustc_incremental-abb292eccc3d42e8.rlib
.rw-r--r-- 644k kkysen  8 Jun 10:20 librustc_index-124a649921cff162.rlib
.rw-r--r--  15M kkysen  8 Jun 10:20 librustc_infer-62f86c9eeb50fcea.rlib
.rw-r--r-- 8.4M kkysen  8 Jun 10:20 librustc_interface-29b752309b9f2f70.rlib
.rw-r--r-- 373k kkysen  8 Jun 10:20 librustc_lexer-fafd113d251357ed.rlib
.rw-r--r-- 7.2M kkysen  8 Jun 10:20 librustc_lint-8e8e34cf84aeabce.rlib
.rw-r--r-- 872k kkysen  8 Jun 10:20 librustc_lint_defs-4ca09eed5c802d68.rlib
.rw-r--r--  29M kkysen  8 Jun 10:20 librustc_llvm-4663d037a8ef38ec.rlib
.rw-r--r-- 703k kkysen  8 Jun 10:20 librustc_log-0e7fd36de276f7eb.rlib
.rwxr-xr-x  15M kkysen  8 Jun 10:20 librustc_macros-0da9b871c4e20306.so*
.rw-r--r--  11M kkysen  8 Jun 10:20 librustc_metadata-fd020a3d609cda95.rlib
.rw-r--r--  50M kkysen  8 Jun 10:20 librustc_middle-1da1ebe73241f7fa.rlib
.rw-r--r-- 7.7M kkysen  8 Jun 10:20 librustc_mir_build-699ff379509e6349.rlib
.rw-r--r-- 5.1M kkysen  8 Jun 10:20 librustc_mir_dataflow-7a9d222a95bfd0fa.rlib
.rw-r--r--  15M kkysen  8 Jun 10:20 librustc_mir_transform-e781fc8784dd88fe.rlib
.rw-r--r-- 2.4M kkysen  8 Jun 10:20 librustc_monomorphize-2c8a940a5b735869.rlib
.rw-r--r-- 7.5M kkysen  8 Jun 10:20 librustc_parse-e51ee450cbbeda4b.rlib
.rw-r--r-- 250k kkysen  8 Jun 10:20 librustc_parse_format-34428493c4d5066b.rlib
.rw-r--r-- 7.0M kkysen  8 Jun 10:20 librustc_passes-d33f27362cb74ada.rlib
.rw-r--r-- 367k kkysen  8 Jun 10:20 librustc_plugin_impl-682e7418726eda10.rlib
.rw-r--r-- 1.7M kkysen  8 Jun 10:20 librustc_privacy-5fd29c315b4e8998.rlib
.rw-r--r--  51M kkysen  8 Jun 10:20 librustc_query_impl-a2f31b52d3526abf.rlib
.rw-r--r-- 2.5M kkysen  8 Jun 10:20 librustc_query_system-931b74f1bc1ec8c6.rlib
.rw-r--r-- 4.4M kkysen  8 Jun 10:20 librustc_rayon-13ba401efe072d28.rlib
.rw-r--r-- 1.0M kkysen  8 Jun 10:20 librustc_rayon_core-6de9f19e5c1bad42.rlib
.rw-r--r--  11M kkysen  8 Jun 10:20 librustc_resolve-f249682aee768d39.rlib
.rw-r--r-- 2.4M kkysen  8 Jun 10:20 librustc_save_analysis-9c03c650c636b99a.rlib
.rw-r--r-- 2.0M kkysen  8 Jun 10:20 librustc_serialize-a7bc65f9b0522bf1.rlib
.rw-r--r-- 5.1M kkysen  8 Jun 10:20 librustc_session-6b7d4c025b0fa518.rlib
.rw-r--r-- 4.7M kkysen  8 Jun 10:20 librustc_span-dea46dae7b161640.rlib
.rw-r--r-- 5.5k kkysen  7 Jun 12:56 librustc_std_workspace_alloc-5ad6d336de25263f.rlib
.rw-r--r-- 7.1k kkysen  7 Jun 12:56 librustc_std_workspace_core-2a6a2797f7a73818.rlib
.rw-r--r-- 8.7k kkysen  7 Jun 12:56 librustc_std_workspace_std-350aa3edc0759e63.rlib
.rw-r--r-- 1.5M kkysen  8 Jun 10:20 librustc_symbol_mangling-4c37bd48c64ff438.rlib
.rw-r--r-- 9.1M kkysen  8 Jun 10:20 librustc_target-379e291363cd612c.rlib
.rw-r--r--  16M kkysen  8 Jun 10:20 librustc_trait_selection-365c4028eed83f05.rlib
.rw-r--r--  10M kkysen  8 Jun 10:20 librustc_traits-0ae2509f20a65c4d.rlib
.rw-r--r-- 2.1M kkysen  8 Jun 10:20 librustc_ty_utils-6c4b3522fa7ed3e8.rlib
.rw-r--r-- 595k kkysen  8 Jun 10:20 librustc_type_ir-47497c627b4737a6.rlib
.rw-r--r--  28M kkysen  8 Jun 10:20 librustc_typeck-c266149761f83822.rlib
.rw-r--r-- 191k kkysen  8 Jun 10:20 libryu-1d701eaa2f8fb816.rlib
.rw-r--r--  28k kkysen  8 Jun 10:20 libscoped_tls-a0b69e194c32841e.rlib
.rw-r--r--  40k kkysen  8 Jun 10:20 libscopeguard-707754673a7bf26d.rlib
.rw-r--r-- 7.6M kkysen  8 Jun 10:20 libserde-c317f2bce6c92943.rlib
.rwxr-xr-x  16M kkysen  8 Jun 10:20 libserde_derive-d42d01eaad6a9355.so*
.rw-r--r-- 2.6M kkysen  8 Jun 10:20 libserde_json-24271d6f052ae883.rlib
.rw-r--r-- 390k kkysen  8 Jun 10:20 libsha1-85f5521f42f13c6f.rlib
.rw-r--r-- 583k kkysen  8 Jun 10:20 libsha2-55a95933f8a9b93c.rlib
.rw-r--r-- 1.4M kkysen  8 Jun 10:20 libsharded_slab-1842799ba5671fe3.rlib
.rw-r--r-- 370k kkysen  8 Jun 10:20 libsmallvec-bc0dc011f2bb4b08.rlib
.rw-r--r-- 668k kkysen  8 Jun 10:20 libsnap-0f94637426a5c31f.rlib
.rw-r--r--  29k kkysen  8 Jun 10:20 libstable_deref_trait-466770d8813df177.rlib
.rw-r--r--  74k kkysen  8 Jun 10:20 libstacker-44c3dace9a1b1294.rlib
.rw-r--r--  18M kkysen  7 Jun 12:56 libstd-fad6565a4a24ca7c.rlib
.rwxr-xr-x 9.2M kkysen  7 Jun 12:56 libstd-fad6565a4a24ca7c.so*
.rw-r--r-- 442k kkysen  7 Jun 12:56 libstd_detect-8e60620ba8892302.rlib
.rw-r--r-- 458k kkysen  8 Jun 10:20 libtempfile-53bce4d3df17deec.rlib
.rw-r--r-- 435k kkysen  8 Jun 10:20 libtermcolor-73356cfb1c625a81.rlib
.rw-r--r--  23k kkysen  8 Jun 10:20 libtermize-399f849dca3f51db.rlib
.rw-r--r-- 7.4M kkysen  7 Jun 12:56 libtest-b81f71b2dfdd83d8.rlib
.rwxr-xr-x 2.9M kkysen  7 Jun 12:56 libtest-b81f71b2dfdd83d8.so*
.rw-r--r-- 1.7M kkysen  8 Jun 10:20 libthorin-62fb5349d25c57df.rlib
.rw-r--r-- 235k kkysen  8 Jun 10:20 libthread_local-afca06f84e40a6ab.rlib
.rw-r--r-- 5.7M kkysen  8 Jun 10:20 libtikv_jemalloc_sys-e0fa2a4725ab11f9.rlib
.rw-r--r-- 572k kkysen  8 Jun 10:20 libtinyvec-fba72a0fdddfeefb.rlib
.rw-r--r-- 648k kkysen  8 Jun 10:20 libtracing-736416193b417442.rlib
.rwxr-xr-x  14M kkysen  8 Jun 10:20 libtracing_attributes-c7423b3acef8df36.so*
.rw-r--r-- 979k kkysen  8 Jun 10:20 libtracing_core-9c601928fc4f031d.rlib
.rw-r--r-- 528k kkysen  8 Jun 10:20 libtracing_log-ad2c31874320e583.rlib
.rw-r--r-- 4.2M kkysen  8 Jun 10:20 libtracing_subscriber-1bdde02238a9d0b0.rlib
.rw-r--r-- 246k kkysen  8 Jun 10:20 libtracing_tree-be1f140334479742.rlib
.rw-r--r-- 3.1M kkysen  8 Jun 10:20 libtypenum-d2a05a278a42827a.rlib
.rw-r--r--  88k kkysen  8 Jun 10:20 libunic_char_property-d1439cef06bb5d76.rlib
.rw-r--r--  76k kkysen  8 Jun 10:20 libunic_char_range-f284ded05f22a84e.rlib
.rw-r--r--  36k kkysen  8 Jun 10:20 libunic_common-01fb028f0a9e6946.rlib
.rw-r--r-- 311k kkysen  8 Jun 10:20 libunic_emoji_char-d65fe45c6dc2fc2c.rlib
.rw-r--r-- 9.9k kkysen  8 Jun 10:20 libunic_ucd_version-dbf542d9648b727b.rlib
.rw-r--r-- 3.3M kkysen  8 Jun 10:20 libunicode_normalization-47476852ddf36e79.rlib
.rw-r--r-- 1.2M kkysen  8 Jun 10:20 libunicode_script-9e6d15a94e8c6ff2.rlib
.rw-r--r-- 3.5M kkysen  8 Jun 10:20 libunicode_security-78dfa49303a97eab.rlib
.rw-r--r-- 150k kkysen  8 Jun 10:20 libunicode_width-a9b790c3f4687f95.rlib
.rw-r--r-- 153k kkysen  7 Jun 12:56 libunicode_width-f10e151a49774d06.rlib
.rw-r--r-- 205k kkysen  8 Jun 10:20 libunicode_xid-c5469705ba991459.rlib
.rw-r--r--  49k kkysen  7 Jun 12:56 libunwind-3b7b15eacc8412be.rlib
```

**Comment by rinon** [comment]
Don't we need the full path to the internal libs to build against the nightly internal libs? They may have changed since we originally did that, they have moved the rustlibs around over time.

**Comment by kkysen** [comment]
`cargo` itself sets `LD_LIBRARY_PATH=$(rustc --print sysroot)/lib`.

> Don't we need the full path to the internal libs to build against the nightly internal libs? They may have changed since we originally did that, they have moved the rustlibs around over time.

Let me check, but it seems to work without that.  We've been running `c2rust-instrument` directly for a while with `LD_LIBRARY_PATH=$(rustc --print sysroot)/lib`, so it probably works.  Also, `LD_LIBRARY_PATH` can only search for `*.so`s, not all the `*.rlib`s in `rustlib`, though I think all the same `*.so`s except for `libLLVM*.so` are in `rustlib`, too.

**Comment by kkysen** [comment]
```shell
kkysen in 🌐 donna in c2rust on  kkysen/rustc-private-link-rpath via 🐍 v3.10.4 via 🦀 v1.60.0-nightly via 🐏 5GiB/39GiB | 463MiB/2GiB took 39ms
at 12:41:52 PM ❯ (cd $(rustc --print sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/lib/ && ll *.so)
.rwxr-xr-x  14M kkysen  8 Jun 10:20 libchalk_derive-b1ba70b71b38b458.so*
.rwxr-xr-x 8.3M kkysen  8 Jun 10:20 libcstr-547a61b22dae33cd.so*
.rwxr-xr-x 119M kkysen  8 Jun 10:20 librustc_driver-f43b82d7671d3119.so*
.rwxr-xr-x  15M kkysen  8 Jun 10:20 librustc_macros-0da9b871c4e20306.so*
.rwxr-xr-x  16M kkysen  8 Jun 10:20 libserde_derive-d42d01eaad6a9355.so*
.rwxr-xr-x 9.2M kkysen  7 Jun 12:56 libstd-fad6565a4a24ca7c.so*
.rwxr-xr-x 2.9M kkysen  7 Jun 12:56 libtest-b81f71b2dfdd83d8.so*
.rwxr-xr-x  14M kkysen  8 Jun 10:20 libtracing_attributes-c7423b3acef8df36.so*

kkysen in 🌐 donna in c2rust on  kkysen/rustc-private-link-rpath via 🐍 v3.10.4 via 🦀 v1.60.0-nightly via 🐏 5GiB/39GiB | 463MiB/2GiB took 4ms
at 12:42:11 PM ❯ (cd $(rustc --print sysroot)/lib/ && ll *.so)
.rw-r--r-- 101M kkysen  7 Jun 12:56 libLLVM-13-rust-1.60.0-nightly.so
.rw-r--r-- 119M kkysen  7 Jun 12:56 librustc_driver-f43b82d7671d3119.so
.rw-r--r-- 9.2M kkysen  7 Jun 12:56 libstd-fad6565a4a24ca7c.so
.rw-r--r-- 2.9M kkysen  7 Jun 12:56 libtest-b81f71b2dfdd83d8.so
```

`lib{std,test,rustc_driver}` are all identical (same hash, different inode).  Then `lib` has `libLLVM*.so` and `rustlib` has `lib{chalk_derive,cst,rustc_macros,serde_derive,tracing_attributes}*.so`.  I don't think we need any of those other ones, right?  If we ever do, I think we can just add both directories to the rpath.

**Comment by kkysen** [comment]
@rinon, @fw-immunant, do you think I should set rpath for both `lib` and `rustlib` just to be safe?  I don't think there's a harm in doing that.

**Comment by rinon** [comment]
> @rinon, @fw-immunant, do you think I should set rpath for both `lib` and `rustlib` just to be safe? I don't think there's a harm in doing that.

Well, I think just lib should be ok, but it will need to be tested thoroughly. If `lib` works, let's just stick with that.

**Comment by kkysen** [comment]
@fw-immunant, setting `$RUSTLIB` is now removed in https://github.com/immunant/c2rust/pull/518/commits/2cbf5fc7808df700d920a0b135fd5a492dbf00f3.

**Comment by kkysen** [comment]
> Well, I think just lib should be ok, but it will need to be tested thoroughly. If `lib` works, let's just stick with that.

Okay, I'll leave that for now, and in case we need it, it's saved here: [`kkysen/rustc-private-link-rpath-rustlib`](https://github.com/immunant/c2rust/tree/kkysen/rustc-private-link-rpath-rustlib).

**Review by fw-immunant — APPROVED** [review]
LGTM. We should also be able to remove `set_env_rustlib` from `rustc-private-link` if this all works, as it's dead now.

**Comment by kkysen** [comment]
Ah yes, I'll remove that.  I'll still leave the `rustlib` method, though, in case we need it.

**Comment by kkysen** [comment]
Also @boyland-pf is now testing it on macOS and if that works it should all be good to go.

**Comment by thedataking** [comment]
I ran `cargo build --all-features` without problems on MacOS 12.5. Nice!

**Comment by kkysen** [comment]
Awesome!  I'll merge then.

**Pull request merged**
