### PR TITLE
Be explicit on the python dependencies

### PR DESCRIPTION
**Pull request by lu-zero**

### CODE REVIEW

**Comment by glguy** [comment]
Would it make sense to create a requirements.txt to help automate this?

https://pip.pypa.io/en/stable/user_guide/#requirements-files

**Comment by lu-zero** [comment]
I guess all depends on how you'd consider eventually distributing the whole package.
Right now it has plenty of moving parts and I guess we are far from a final state.

A `requirements.txt` and mention of it in the README.md would be surely good for newcomers like me :)

**Comment by thedataking** [comment]
@glguy yes, I added a `requirements.txt` file and updated the build scripts to use it on the internal branch. I'll update the README to mention it.

**Comment by thedataking** [comment]
Closing issue. `README.md` has been updated to explain how to (mostly) automatically provision a build environment. Thanks for the suggestion @lu-zero!

**Pull request closed without merging**
