### PR TITLE
[WIP] Remove  #![feature(label_break_value)]  (fix #731)

### LINKED ISSUE #731: Remove `#![feature(label_break_value)]` as it's been stabilized
`#![feature(label_break_value)]` has now been stabilized in 1.65 (see https://github.com/rust-lang/rust/pull/99332, https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html#break-from-labeled-blocks).

### PR DESCRIPTION
**Pull request by bungcip**
remove `#![feature(label_break_value)]` from generated rust source file.
rust-toolchain is updated to `nightly-2022-10-25`

### CODE REVIEW

**Comment by bungcip** [comment]
unit test fail in `tests/filecheck/aggregate1.rs`:
original aggregate1.rs.analysis.txt :
```
Aggregate literal label: Label { origin: None, origin_params: [('a, Origin(4)), ('h0, Origin(5))], perm: (empty) }#S[]
```
after upgrading rust-toolchain:
```
Aggregate literal label: Label { origin: None, origin_params: [('a, Origin(4)), ('h0, Origin(5))], perm: (empty) }#S<'_>[]
```

checking `c2rust-analyze/src/labeled_ty.rs` :

```
impl<'tcx, L: fmt::Debug> fmt::Debug for LabeledTyS<'tcx, L> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}#{:?}{:?}", self.label, self.ty, self.args)
    }
}
```
`self.ty` is `rustc_middle::ty::Ty`.  maybe the output format changed -_-;
need more investigation...

**Comment by rinon** [comment]
Thanks for working on this! There's two separate things going on here, rolling the toolchain forward and removing the then unnecessary feature. The commit message/title should at least reflect this, as rolling the toolchain version is more important than the feature removal. The feature removal is small enough of a change that I think it's ok to combine with the toolchain bump.

This looks mostly fine once expected test output is updated. However the cast changes of Misc to PtrToPtr are a bit unexpected. I assume the compiler removed Misc, but that cast was for pointer to usize casts, which doesn't seem like a PtrToPtr cast.

@spernsteiner @aneksteind is bumping the toolchain forward ok with what you're in the middle of right now?

**Comment by spernsteiner** [comment]
`c2rust-analyze` changes look good to me.

>is bumping the toolchain forward ok with what you're in the middle of right now?

Fine with me, as long as everything builds and tests still pass.

>However the cast changes of Misc to PtrToPtr are a bit unexpected. I assume the compiler removed Misc, but that cast was for pointer to usize casts, which doesn't seem like a PtrToPtr cast.

They've broken up `Misc` into a bunch of more specific variants: https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/mir/enum.CastKind.html
Pointer to usize falls under the new `CastKind::PointerExposeAddress`

**Comment by kkysen** [comment]
Hi @bungcip, thanks for working on this!  I wanted to let you know, though, that we've already previously worked on updating the toolchain to a more recent version in #811, but have since closed that PR as updating the toolchain wasn't a priority for us yet (in the long term, it is helpful, though).  I just wanted to let you know so you don't accidentally redo work already done, and so you can look at that PR for help in updating the toolchain (it contains some other necessary fixes, including a bug fix, along with reasoning).  The `clippy` fixes in that PR need to be removed as they were since removed in `clippy` in a Rust patch release, but otherwise it should still be applicable besides needing a rebase.

Specifically for `PtrToPtr`, that is the correct cast in that situation.  It's a fat to thin ptr cast that's done immediately before the thin ptr to `usize` cast.

**Pull request closed without merging**
