### PR TITLE
transpile: fix `curl` transpile breakage while maintaining a total `SrcLoc` order

### PR DESCRIPTION
**Pull request by kkysen**
#1128 fixed the non-total (non-transitive) `SrcLoc` ordering, but accidentally broke the `curl` transpilation test in `c2rust-testsuites`, which is tested in CI, but was broken for external contributors PRs (fixed now in #1159).

In the `curl` transpilation, a couple of `use` imports (`__sigset_t` and `C2RustUnnamed_4`) were missing, cause the build to fail afterward.

I'm still not exactly sure why this fixes the issue while maintaining a transitive, total order, but it passes the total order test and transpiles `curl` correctly now.  Hopefully this is a complete fix, and I didn't just fix a one-off error in `curl`.

* 9679a3be is the real fix.
* a4a052b3 are generally useful for testing and debugging.

### CODE REVIEW

**Comment by kkysen** [comment]
@Kriskras99, does this still also fix the crash you were seeing in #1126?

**Comment by Kriskras99** [comment]
Still fixes the crash!

**Comment by kkysen** [comment]
> Still fixes the crash!

Awesome!!

**Review by fw-immunant — APPROVED** [review]
This looks sane; it's easier to review by looking at the cumulative diff since df42b55eae9ecfd4380004a513a10526ef8776cf: `git diff df42b55eae9ecfd4380004a513a10526ef8776cf..9679a3befb9d5d9431ee7db4d967347edb64536d -- c2rust-transpile/src/c_ast/mod.rs`

**Pull request merged**
