### PR TITLE
Make the PDG textual representation even more readable

### PR DESCRIPTION
**Pull request by kkysen**
I modified the PDG textual representation again to make it more readable:
* `bb: {bb}, stmt: {stmt}` => `bb{bb}[{stmt}]`: inspired by @spernsteiner's slides
* `src: {src}, dest: {dest}` => `{src} => {dest}`
* `node {node_id}` => `n[{node_id}]`: also tried `n{node_id}` but allows for out-of-the-box syntax highlighting (if we pretend it's Rust)
* `graph {graph_id}` => `g[{graph_id}]`
* trailing `;`: for syntax highlighting
* padded the columns so it's easier to read

New formatting:

```rust
g[1098] {
	n[0]:  malloc(n = 1) _     => _3        @ bb1[2]:  fn fdnode_init;                  
	n[1]:  copy          n[0]  => _2        @ bb2[3]:  fn fdnode_init;                  
	n[2]:  copy          n[1]  => _10       @ bb2[10]: fn fdnode_init;                  
	n[3]:  copy          n[2]  => _1        @ bb0[0]:  fn is_null;                      
	n[4]:  copy          n[1]  => _0        @ bb9[3]:  fn fdnode_init;                  
	n[5]:  copy          n[4]  => _11       @ bb2[0]:  fn fdevent_register;             
	n[6]:  value.store   n[5]  => _6.Deref  @ bb2[1]:  fn fdevent_register;             
	n[7]:  value.load    _     => _12       @ bb2[4]:  fn fdevent_register;             
	n[8]:  field.0       n[7]  => _13       @ bb2[7]:  fn fdevent_register;             
	n[9]:  addr.store    n[8]  => _         @ bb2[10]: fn fdevent_register;             
	n[10]: field.2       n[7]  => _         @ bb2[14]: fn fdevent_register;             
	n[11]: addr.store    n[10] => _         @ bb2[14]: fn fdevent_register;             
	n[12]: field.1       n[7]  => _16       @ bb2[17]: fn fdevent_register;             
	n[13]: addr.store    n[12] => _         @ bb2[20]: fn fdevent_register;             
	n[14]: field.3       n[7]  => _         @ bb2[24]: fn fdevent_register;             
	n[15]: addr.store    n[14] => _         @ bb2[24]: fn fdevent_register;             
	n[16]: field.4       n[7]  => _         @ bb3[0]:  fn fdevent_register;             
	n[17]: addr.store    n[16] => _         @ bb3[0]:  fn fdevent_register;             
	n[18]: copy          n[7]  => _0        @ bb3[3]:  fn fdevent_register;             
	n[19]: copy          n[18] => _15       @ bb4[0]:  fn connection_accepted;          
	n[20]: value.store   n[19] => _14.Deref @ bb4[5]:  fn connection_accepted;          
	n[21]: value.load    _     => _22       @ bb8[19]: fn connection_close;             
	n[22]: copy          n[21] => _2        @ bb0[0]:  fn fdevent_fdnode_event_del;     
	n[23]: copy          n[22] => _5        @ bb0[4]:  fn fdevent_fdnode_event_del;     
	n[24]: copy          n[23] => _1        @ bb0[0]:  fn is_null;                      
	n[25]: copy          n[22] => _8        @ bb2[5]:  fn fdevent_fdnode_event_del;     
	n[26]: copy          n[25] => _2        @ bb0[0]:  fn fdevent_fdnode_event_unsetter;
	n[27]: field.4       n[26] => _8        @ bb1[3]:  fn fdevent_fdnode_event_unsetter;
	n[28]: addr.load     n[27] => _         @ bb1[3]:  fn fdevent_fdnode_event_unsetter;
	n[29]: value.load    _     => _3        @ bb1[3]:  fn fdevent_unregister;           
	n[30]: copy          n[29] => _12       @ bb1[12]: fn fdevent_unregister;           
	n[31]: ptr_to_int    n[30] => _         @ bb1[12]: fn fdevent_unregister;           
	n[32]: copy          n[29] => _22       @ bb8[8]:  fn fdevent_unregister;           
	n[33]: copy          n[32] => _1        @ bb0[0]:  fn fdnode_free;                  
	n[34]: copy          n[33] => _4        @ bb0[4]:  fn fdnode_free;                  
	n[35]: copy          n[34] => _3        @ bb0[5]:  fn fdnode_free;                  
	n[36]: free          n[35] => _2        @ bb0[6]:  fn fdnode_free;                  
}
```

Old formatting:

```rust
graph 1098 {
	node 0: (fn fdnode_init) malloc(n = 1) { src: _, dest: _3, bb: 1, stmt: 2 },
	node 1: (fn fdnode_init) copy { src: node 0, dest: _2, bb: 2, stmt: 3 },
	node 2: (fn fdnode_init) copy { src: node 1, dest: _10, bb: 2, stmt: 10 },
	node 3: (fn is_null) copy { src: node 2, dest: _1, bb: 0, stmt: 0 },
	node 4: (fn fdnode_init) copy { src: node 1, dest: _0, bb: 9, stmt: 3 },
	node 5: (fn fdevent_register) copy { src: node 4, dest: _11, bb: 2, stmt: 0 },
	node 6: (fn fdevent_register) value.store { src: node 5, dest: _6.Deref, bb: 2, stmt: 1 },
	node 7: (fn fdevent_register) value.load { src: _, dest: _12, bb: 2, stmt: 4 },
	node 8: (fn fdevent_register) field.0 { src: node 7, dest: _13, bb: 2, stmt: 7 },
	node 9: (fn fdevent_register) addr.store { src: node 8, dest: _, bb: 2, stmt: 10 },
	node 10: (fn fdevent_register) field.2 { src: node 7, dest: _, bb: 2, stmt: 14 },
	node 11: (fn fdevent_register) addr.store { src: node 10, dest: _, bb: 2, stmt: 14 },
	node 12: (fn fdevent_register) field.1 { src: node 7, dest: _16, bb: 2, stmt: 17 },
	node 13: (fn fdevent_register) addr.store { src: node 12, dest: _, bb: 2, stmt: 20 },
	node 14: (fn fdevent_register) field.3 { src: node 7, dest: _, bb: 2, stmt: 24 },
	node 15: (fn fdevent_register) addr.store { src: node 14, dest: _, bb: 2, stmt: 24 },
	node 16: (fn fdevent_register) field.4 { src: node 7, dest: _, bb: 3, stmt: 0 },
	node 17: (fn fdevent_register) addr.store { src: node 16, dest: _, bb: 3, stmt: 0 },
	node 18: (fn fdevent_register) copy { src: node 7, dest: _0, bb: 3, stmt: 3 },
	node 19: (fn connection_accepted) copy { src: node 18, dest: _15, bb: 4, stmt: 0 },
	node 20: (fn connection_accepted) value.store { src: node 19, dest: _14.Deref, bb: 4, stmt: 5 },
	node 21: (fn connection_close) value.load { src: _, dest: _22, bb: 8, stmt: 19 },
	node 22: (fn fdevent_fdnode_event_del) copy { src: node 21, dest: _2, bb: 0, stmt: 0 },
	node 23: (fn fdevent_fdnode_event_del) copy { src: node 22, dest: _5, bb: 0, stmt: 4 },
	node 24: (fn is_null) copy { src: node 23, dest: _1, bb: 0, stmt: 0 },
	node 25: (fn fdevent_fdnode_event_del) copy { src: node 22, dest: _8, bb: 2, stmt: 5 },
	node 26: (fn fdevent_fdnode_event_unsetter) copy { src: node 25, dest: _2, bb: 0, stmt: 0 },
	node 27: (fn fdevent_fdnode_event_unsetter) field.4 { src: node 26, dest: _8, bb: 1, stmt: 3 },
	node 28: (fn fdevent_fdnode_event_unsetter) addr.load { src: node 27, dest: _, bb: 1, stmt: 3 },
	node 29: (fn fdevent_unregister) value.load { src: _, dest: _3, bb: 1, stmt: 3 },
	node 30: (fn fdevent_unregister) copy { src: node 29, dest: _12, bb: 1, stmt: 12 },
	node 31: (fn fdevent_unregister) ptr_to_int { src: node 30, dest: _, bb: 1, stmt: 12 },
	node 32: (fn fdevent_unregister) copy { src: node 29, dest: _22, bb: 8, stmt: 8 },
	node 33: (fn fdnode_free) copy { src: node 32, dest: _1, bb: 0, stmt: 0 },
	node 34: (fn fdnode_free) copy { src: node 33, dest: _4, bb: 0, stmt: 4 },
	node 35: (fn fdnode_free) copy { src: node 34, dest: _3, bb: 0, stmt: 5 },
	node 36: (fn fdnode_free) free { src: node 35, dest: _2, bb: 0, stmt: 6 },
}
```

What do others think?  @aneksteind

### CODE REVIEW

**Review by aneksteind — APPROVED** [review]
I'm not 100% in love with the syntax for when the destination is empty, i.e. `n[8]  => _`, but the rest looks fine to me. I'm not sure what else I would choose, but it feels odd that there's a `=>` at all in that sort of situation.

**Comment by aneksteind** [comment]
Ditto with when the source is empty

**Comment by thedataking** [comment]
I haven't worked directly with the PDG so I'm probably not the most qualified to comment here. That said, I'm not sure your proposed representation has enough benefits (again, speaking for myself here) to justify the amount of code you needed to add.

Did you consider outputting the graph in the dot format so it can be visualized by [graphviz](http://www.graphviz.org/)? Again, this is probably only justified if folks with more PDG experience than I think they'd use such a feature regularly.

**Comment by kkysen** [comment]
@aneksteind, I put `_` initially for the destination since the other `MirPlace`s use `_` as their prefix, so it'd be `_1` vs. `_`.  That makes less sense for the source, a `NodeId`, but I wasn't sure what to choose instead.  I could use `None`, though I thought that looked much clunkier, but I think for sure `Some`s are excessive.

@thedataking, I have been thinking of using graphviz for the PDGs if it's easy enough to do and worth it, but I think there's also value in having a concise, columnar format like this that lets me quickly visually scan through graphs by field/column, such as easily visually seeing where sources or destinations are empty, seeing which `NodeKind`s are used, and which functions the `Node`s are happening in.  Anyways, there's not that much extra code besides `pad_columns`, which I could skip, but it's already written, and I've so far found it useful for quickly inspecting PDGs.

**Comment by aneksteind** [comment]
I think the columnar layout is a net positive and so is worth merging for that reason.

I don't want to bike-shed, so I won't prescribe or suggest what the syntax should be changed to, but if there was an alternative to the source/dest syntax that you could think of then I'd be open to looking at it. However I don't think it's worth spending too much time on. 

I think Per has a point in that, if we expect the representation of the PDG to change moving forward, then we've introduced a potential maintenance burden. 

Something that might be worth considering later on is implementing a function to convert our representation to a `petgraph` graph -- then we get dotfile output and algorithms [for free](https://docs.rs/petgraph/latest/petgraph/dot/index.html).

**Comment by kkysen** [comment]
I don't currently have any better alternatives for the source/dest in mind, but it's pretty easy to change again if we think of a better way later.

Regarding a potential maintenance burden, there's not really significantly more of a burden than previously if the PDG representation changes.

`petgraph` is a good idea moving forward if that works out.

**Pull request merged**
