### PR TITLE
Transfer the packed attribute on unions to repr(packed)

### PR DESCRIPTION
**Pull request by chrysn**
Closes: https://github.com/immunant/c2rust/issues/346

---

This should be a straightforward solution to #346, and works for me on RIOT (which also means I can't easily test it on the main branch, as I still need my for-riot vendor branch that has #311 and the branch mentioned in #309 merged).

There are no tests yet; is

```
$ cargo +nightly-20109-12-05 build --locked --release
$  python3 scripts/test_translator.py ./tests
```

the right procedure?

### CODE REVIEW

**Comment by thedataking** [comment]
@chrysn the Darwin failures were due to timeouts as far as I can tell. I've opened a PR to get CI working properly again.

**Comment by chrysn** [comment]
Is there anything that should be addressed about this PR? Does it help if I rebase it onto current master?

**Comment by thedataking** [comment]
LTGM but I'm no expert on packed unions so I'd like a second pair of eyes before we merge. And yes, rebasing onto current master would be nice.

**Comment by chrysn** [comment]
As for the correctness of the built unions, the way I'm using them
frequently transmutes them back and forth between parts generated by
bindgen and those generated by C2Rust. As part of these transmutes, I'm
checking the size behind the pointer -- and they match ever since I'm on
this branch.

Rebased onto master and pushed for consumption by the CI; I haven't run
my full use case (which does these tests as part of everyday operation)
on the rebased branch yet.

**Comment by chrysn** [comment]
I've given the rebased packed-unions a test run. Most tests also merged in the minimal-309 branch referenced in https://github.com/immunant/c2rust/issues/309#issuecomment-696671353, as that's necessary for other parts of the code. As expected, that branch has passed the inline casting tests (asserting that bindgen's view of the C structs is as large as C2Rust's), which current master plus minimal-309 does not).

**Review by fw-immunant — APPROVED** [review]
This LGTM and does what it says on the tin. I think we should merge.

**Comment by fw-immunant** [comment]
I think it's worth noting separately, however, that we still have some holes in our support of the `packed` attribute--it isn't respected yet for struct or union fields, and somewhat relatedly we still have #136 outstanding. In `docs/known-limitations.md` we mention missing GNU packed struct support--this should probably be clarified to describe exactly which meanings/contexts of `__attribute__((packed))` we support.

**Pull request merged**
